---
# tasks file for roles/java_tomcat

- name: Install wget
  apt:
    name: wget
    state: present

- name: Download Apache Tomcat 7
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
    dest: /home/ubuntu/apache-tomcat-7.0.94.tar.gz
    mode: '0644'

- name: Extract Apache Tomcat
  unarchive:
    src: /home/ubuntu/apache-tomcat-7.0.94.tar.gz
    dest: /home/ubuntu/
    remote_src: yes

- name: Make Tomcat startup script executable
  file:
    path: /home/ubuntu/apache-tomcat-7.0.94/bin/startup.sh
    mode: '0755'

- name: Start Tomcat
  shell: ./startup.sh
  args:
    chdir: /home/ubuntu/apache-tomcat-7.0.94/bin/
...
