- name: Create KOPS Cluster
  hosts: k8s-master
  become: yes
  tasks:
    - name: Create KOPS cluster
      shell: |
        kops create cluster \
          --state=s3://k8s-cal-state-bucket \
          --zones=us-east-2a,us-east-2b \
          --node-count=2 \
          --name=cal.k8s.local \
          --yes
      environment:
        KOPS_STATE_STORE: s3://k8s-cal-state-bucket
...
