- name: Delete KOPS Cluster
  hosts: k8s-master
  become: yes
  tasks:
    - name: Delete KOPS cluster
      shell: kops delete cluster --name=cal.k8s.local --state=s3://k8s-cal-state-bucket --yes
...
