---
- name: Deploy Calculator App to Kubernetes
  hosts: k8s-master
  become: yes
  tasks:

    - name: Copy sevice.yml to Kubernetes master
      copy:
        src: ../../kubernetes/service.yml
        dest: /tmp/service.yml

    - name: Apply Kubernetes manifest
      shell: kubectl apply -f /tmp/service.yml
      environment:
        KUBECONFIG: /root/.kube/config
...

