---
- name: Get Kubernetes service info
  hosts: k8s-master
  tasks:
    - name: Run kubectl get svc for calc-service
      command: kubectl get svc calc-service -o json
      environment:
        KUBECONFIG: /root/.kube/config
      register: svc_info

    - name: Show service JSON
      debug:
        var: svc_info.stdout
...
