---
- name: Create Kubernetes Cluster with KOPS
  hosts: ansibleMaster
  become: true
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Update Kubernetes cluster with KOPS
      shell: |
        kops update cluster \
        --name={{ cluster_name }} \
        --yes \
        --state=s3://{{ s3_bucket }}
      environment:
        KOPS_STATE_STORE: "s3://{{ s3_bucket }}"
        AWS_DEFAULT_REGION: "{{ region }}"
...
